spring:
  application:
    name: CTReview
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
      show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console



# 콘솔 버전의 간격을 그대로
review:
  unit: DAYS
  steps:
    1: [1, 3, 7, 30]
    2: [3, 7, 30]
    3: [7, 30]
